plugins {
    id 'java'
    id "xyz.wagyourtail.unimined" version "1.4.2-SNAPSHOT"
}

group = project_group
version = mod_version

base {
    archivesName = mod_id
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

sourceSets {
    fabric
    neoforge
}

configurations {
    mainImplementation
}

repositories {
    unimined.neoForgedMaven()
    unimined.spongeMaven
    unimined.wagYourMaven("releases")
    unimined.modrinthMaven()

    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.terraformersmc.com/releases/" }

    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }

    exclusiveContent {
        forRepository {
            maven {
                name = 'GeckoLib'
                url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
            }
        }
        filter { includeGroupAndSubgroups('com.geckolib') }
    }
}

unimined.minecraft {
    version minecraft_version

    mappings {
        mojmap()
    }

    defaultRemapJar = false
}

unimined.minecraft(sourceSets.fabric) {
    combineWith(sourceSets.main)

    fabric {
        loader project.fabric_loader
    }

    defaultRemapJar = true
}

unimined.minecraft(sourceSets.neoforge) {
    combineWith(sourceSets.main)

    neoForge {
        loader project.neoforge_version
    }

    defaultRemapJar = true
}

dependencies {
    neoforgeModImplementation "com.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"

    fabricModImplementation "com.geckolib:geckolib-fabric-${minecraft_version}:${geckolib_version}"
    fabricModImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api}"
    fabricCompileOnly "com.terraformersmc:modmenu:${modmenu_version}"
    fabricCompileOnly "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forgeconfigapiport_version}"

    // Just to resolve it in common
    modImplementation "com.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"
    compileOnly "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${forgeconfigapiport_version}"
}

processResources {
    exclude("models") // BlockBench project dir
    exclude("assets/${mod_id}/models/item/halos.json") // 1.21 items
    exclude("assets/${mod_id}/geckolib/geo") // Old geo folder

    from("src/main/resources/assets/${mod_id}/geckolib/geo") {
        into "assets/${mod_id}/geckolib/models"
    }
}

processFabricResources {
    def buildProps = project.properties.clone()

    filesMatching("fabric.mod.json") {
        expand buildProps
    }
}

processNeoforgeResources {
    def buildProps = project.properties.clone()

    filesMatching("META-INF/neoforge.mods.toml") {
        expand buildProps
    }
}

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}
compileTestJava.enabled = false
