plugins {
    id 'multiloader-common'
}

configurations {
    commonJava {
        canBeResolved = true
    }
    commonResources {
        canBeResolved = true
    }
}

dependencies {
    compileOnly(project(':common')) {
        def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
    commonJava(project(path: ':common', configuration: 'commonJava'))
    commonResources(project(path: ':common', configuration: 'commonResources'))
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

tasks.register('copyToRootLibs', Copy) {
    from(layout.buildDirectory.dir('libs'))
    into rootProject.layout.buildDirectory.dir('libs')
}

tasks.named('build') {
    finalizedBy 'copyToRootLibs'
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}