license="LGPL-3.0"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/mod/blue-archive-halos-pyroxene"
issueTrackerURL="https://github.com/kepalakubik/Pyroxene/issues"
#updateJSONURL="https://change.me.example.invalid/updates.json"
logoFile="assets/${mod_id}/icon.png"
credits="spicywolfoffical (original creator)"
authors="${mod_author}"
description="A rewrite of the Blue Archive Halos mod with additional features, improvements, and support for the latest Minecraft versions."

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[26.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[26.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="geckolib"
type="required"
versionRange="[5.4,)"
ordering="NONE"
side="BOTH"
