plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
}

dependencies {
    implementation "com.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"
    api("fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${forgeconfigapiport_version}")
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources(sourceSets.main.output.resourcesDir) {
        builtBy processResources
    }
}

// Move the geckolib contents into the mod assets
processResources {
    exclude("assets/${mod_id}/geckolib/spicywolfoffical") // Copyrighted assets

    def wolfDir = "src/main/resources/assets/${mod_id}/geckolib/spicywolfoffical"
    def geckoDir = "assets/${mod_id}/geckolib"

    from("${wolfDir}/animations") { into("${geckoDir}/animations") }
    from("${wolfDir}/textures") { into("${geckoDir}/textures") }
    from("${wolfDir}/geo") { into("${geckoDir}/models") }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}
